all:
	gcc p1-socket.c -o p1-socket;
	gcc p2-socket.c -o p2-socket;
	gcc p1-fifo.c -o p1-fifo;
	gcc p2-fifo.c -o p2-fifo;
	gcc p1-shm.c -o p1-shm;
	gcc p2-shm.c -o p2-shm;

socket:
	gcc p1-socket.c -o p1-socket;
	gcc p2-socket.c -o p2-socket;

fifo:
	gcc p1-fifo.c -o p1-fifo;
	gcc p2-fifo.c -o p2-fifo;

shm:
	gcc p1-shm.c -o p1-shm;
	gcc p2-shm.c -o p2-shm;